/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventana;

import Clase.Clase;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author CECYTEM
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
private int niveles = 0;

    public Ventana() {
        initComponents();
            
        setSize(515, 450); 
        setTitle("Ahorcado");
        setLocationRelativeTo(null);
        setResizable(false);
        this.repaint();
        dispose();     
        jButton1.setEnabled(false);
        jTextField1.setVisible(false);
        jButton4.setEnabled(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        imprimir = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        Nivel = new javax.swing.JLabel();
        err3 = new javax.swing.JLabel();
        numnivel = new javax.swing.JLabel();
        err = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(102, 102, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Digite una letra:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 210, 200, 48);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(190, 320, 140, 50);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(360, 320, 140, 50);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(230, 220, 40, 30);

        imprimir.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        getContentPane().add(imprimir);
        imprimir.setBounds(50, 120, 290, 50);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("Start");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(10, 320, 140, 50);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agre.png"))); // NOI18N
        jButton4.setText("Siguiente nivel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(10, 270, 490, 40);

        Nivel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Nivel.setText("Nivel:");
        getContentPane().add(Nivel);
        Nivel.setBounds(410, 110, 50, 40);

        err3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        err3.setText("errores:");
        getContentPane().add(err3);
        err3.setBounds(400, 70, 60, 40);

        numnivel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numnivel.setText("0");
        getContentPane().add(numnivel);
        numnivel.setBounds(470, 110, 10, 40);

        err.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        err.setText("0");
        getContentPane().add(err);
        err.setBounds(470, 70, 10, 40);

        jButton6.setText("¿Como jugar?");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(360, 30, 130, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 0, 106, 106);

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Juego del Ahorcado");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 20, 231, 44);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       //int num;
       //num=Integer.parseInt(jTextField1.getText());
      Clase c=new Clase();
      String TEXTO;
      char TEXTO2 = 0; 
      
      TEXTO=String.valueOf(jTextField1.getText());
      TEXTO2=TEXTO.charAt(0);

       c.guionXLetra(TEXTO2,niveles);
       imprimir.setText(c.getCadena());
       
       if (imprimir.getText().equals(c.getPabra(niveles)))
           jButton4.setEnabled(true);
       else 
           jButton4.setEnabled(false);
       
       //---------------Error----------------//
       c.imgError(niveles, TEXTO);

       
       if (c.getError()>=6){
        
        err.setText("0");
        imprimir.setText(null);
        jTextField1.setText(null);
        niveles=0;
        jButton3.setEnabled(true);
        jButton1.setEnabled(false);}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Clase c=new Clase();
        
        imprimir.setText(c.calGuion(niveles));
        
        jButton1.setEnabled(true);
        jTextField1.setVisible(true);
        jButton4.setEnabled(false);
        jButton3.setEnabled(false);
        
        if (niveles==6){

        JOptionPane.showMessageDialog(null,"**A ganado**, Felicidades" + "\n¿Quiere que el juego se reinicie?");
        err.setText("0");
        
        jButton1.setVisible(false);
        jButton3.setEnabled(false);
        niveles=0;
        numnivel.setText("0");
        }    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String txt;
        Clase c=new Clase();

        
       
        
        txt=imprimir.getText();
        System.out.println(txt);
        if (txt.equals(c.getPabra(niveles))){
          niveles=niveles+1;
          numnivel.setText(""+niveles);
          jButton3.setEnabled(true);
          jButton4.setEnabled(false);
          jButton1.setEnabled(false); 
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        JOptionPane.showMessageDialog(null,"El juego consiste en adivinar la palabra oculta. \n Para ganar pon las letras correctas. \n Solo tienes 6 intentos.");
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel Nivel;
    public static javax.swing.JLabel err;
    public static javax.swing.JLabel err3;
    public static javax.swing.JLabel imprimir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    public static javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JTextField jTextField1;
    public static javax.swing.JLabel numnivel;
    // End of variables declaration//GEN-END:variables
}
